# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 13:10
from __future__ import unicode_literals

from django.db import models, migrations


def create_director(apps, schema_editor):
    from user.models import MyUser
    from django.conf import settings
    director = settings.INITIAL_DIRECTOR
    MyUser.objects.create_director(**director)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_director),
    ]
