# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationtype', '0001_initial'),
        ('operation', '0001_initial'),
        ('product', '0003_auto_20170802_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operations',
            field=models.ManyToManyField(through='operation.Operation', to='operationtype.OperationType'),
        ),
    ]
