# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'product photo', 'verbose_name_plural': 'product photos'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productphoto',
            table='product_photo',
        ),
    ]
