# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170818_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='operations',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
