# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtype',
            options={'verbose_name': 'operation type', 'verbose_name_plural': 'operation types'},
        ),
        migrations.AlterModelTable(
            name='operationtype',
            table='operation_type',
        ),
    ]
