# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationtypecategory', '0001_initial'),
        ('operationtype', '0002_auto_20170818_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operationtypecategory.OperationTypeCategory'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='full_cost',
            field=models.FloatField(blank=True),
        ),
    ]
