# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brigade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={'verbose_name': 'brigade', 'verbose_name_plural': 'brigades'},
        ),
        migrations.AlterModelTable(
            name='brigade',
            table='brigade',
        ),
    ]
