# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170818_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operationtype.OperationType'),
        ),
    ]
