# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
        ('worker', '0002_auto_20170804_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.PositiveIntegerField(blank=True, default=0)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Operation')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_operations',
            field=models.ManyToManyField(through='worker.WorkerOperation', to='operation.Operation'),
        ),
    ]
