# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20170808_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='is_active',
            new_name='is_working',
        ),
        migrations.AddField(
            model_name='worker',
            name='monthly_salary',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
