# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20170809_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='time_worked',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
