# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_worker_time_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='reset_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
