# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_worker_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='reset_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
