# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_auto_20170810_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='reset_date',
            new_name='last_reset',
        ),
    ]
