# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_auto_20170810_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
