# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_auto_20170810_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
