# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_auto_20170810_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='last_reset',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='time_worked',
        ),
    ]
