# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0014_auto_20170815_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='last_reset_done',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_reset_salary',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='workeroperation',
            name='done',
        ),
    ]
