# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_auto_20170815_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AlterModelOptions(
            name='workeroperation',
            options={'verbose_name': 'worker operation', 'verbose_name_plural': 'worker operations'},
        ),
        migrations.AlterModelTable(
            name='worker',
            table='worker',
        ),
        migrations.AlterModelTable(
            name='workeroperation',
            table='worker_operation',
        ),
    ]
