# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0016_auto_20170818_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.FloatField(null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'goal',
                'db_table': 'goal',
                'verbose_name_plural': 'goals',
            },
        ),
        migrations.RemoveField(
            model_name='worker',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working',
        ),
    ]
