# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0018_worker_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='goal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Goal'),
        ),
    ]
