# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost_per_second', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'operation type categories',
                'db_table': 'operation_type_category',
                'verbose_name': 'operation type category',
            },
        ),
    ]
