# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
        ('product', '0001_initial'),
        ('public', '0001_initial'),
        ('operationtype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertiming',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker'),
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='operation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationtype.OperationType'),
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker'),
        ),
    ]
