# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20170809_1334'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField()),
                ('delta', models.DurationField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
    ]
