# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20170810_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workertiming',
            name='start',
        ),
        migrations.AddField(
            model_name='workertiming',
            name='action',
            field=models.CharField(choices=[('start', 'start'), ('stop', 'stop'), ('reset', 'reset')], default='start', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workertiming',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
