# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
        ('public', '0007_auto_20170815_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workeroperationlogs',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.Operation'),
        ),
    ]
