# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_auto_20170815_1521'),
        ('public', '0008_auto_20170815_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('date', models.DateTimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
