# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_payrolldates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayrollDates',
            new_name='Payroll',
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['date'], 'verbose_name': 'payroll', 'verbose_name_plural': 'payrolls'},
        ),
        migrations.AlterModelOptions(
            name='workeroperationlogs',
            options={'verbose_name': 'worker operation log', 'verbose_name_plural': 'worker operation logs'},
        ),
        migrations.AlterModelOptions(
            name='workertiming',
            options={'ordering': ['date'], 'verbose_name': 'worker timing', 'verbose_name_plural': 'worker timings'},
        ),
        migrations.AlterModelTable(
            name='payroll',
            table='payroll',
        ),
        migrations.AlterModelTable(
            name='workeroperationlogs',
            table='worker_operation_logs',
        ),
        migrations.AlterModelTable(
            name='workertiming',
            table='worker_timing',
        ),
    ]
