# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20170818_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
