# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_auto_20170902_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workeroperationlogs',
            name='cost',
        ),
    ]
