# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationtype', '0005_auto_20170831_1117'),
        ('public', '0012_remove_workeroperationlogs_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workeroperationlogs',
            name='operation',
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='cost',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workeroperationlogs',
            name='operation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationtype.OperationType'),
        ),
    ]
