# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20170915_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workertiming',
            options={'verbose_name': 'worker timing', 'verbose_name_plural': 'worker timings'},
        ),
        migrations.RemoveField(
            model_name='workertiming',
            name='action',
        ),
        migrations.RemoveField(
            model_name='workertiming',
            name='date',
        ),
        migrations.AddField(
            model_name='workertiming',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 10, 48, 32, 942781, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workertiming',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
